(()=>{
 const payments=document.getElementById('payments-section'),notifications=document.getElementById('founder-notifications-section'),list=document.getElementById('founder-notifications-list'),qr=document.getElementById('admin-payment-qr'),file=document.getElementById('payment-qr-file'),save=document.getElementById('payment-qr-save'),message=document.getElementById('payment-settings-message'),notice=document.getElementById('founder-notifications-message');
 let code,version=0,controller,timer,uploading=false;
 function clear(){payments.hidden=true;notifications.hidden=true;list.replaceChildren();qr.hidden=true;qr.removeAttribute('src');file.value='';message.textContent='';notice.textContent='';}
 async function post(path,fields={}){const response=await fetch('/api/admin/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code,...fields}),cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])});if(!response.ok)throw Error('Unavailable');return response.json();}
 async function load(){const current=version;try{
  const [settings,matches]=await Promise.all([post('payment-settings'),post('founder-matches')]);if(current!==version)return;
  payments.hidden=false;notifications.hidden=false;qr.hidden=!settings.qrUrl;if(settings.qrUrl)qr.src=settings.qrUrl;else qr.removeAttribute('src');list.replaceChildren();
  for(const founder of matches.founders){const article=document.createElement('article');article.dataset.notificationId=founder.notificationId;const heading=document.createElement('h3'),info=document.createElement('p'),fit=document.createElement('p');heading.textContent=founder.name;info.textContent=founder.company+' / '+founder.operatorName;fit.textContent='Fit score '+founder.score+'/100';article.append(heading,info,fit);
   if(founder.founderLink){const first=founder.name.trim().split(/\s+/u)[0]||'there';const text=`Hi ${first}, Besto's AI has found a new operator who matches your pilot ask. They haven't been contacted yet. See your updated matches: ${founder.founderLink}`;const button=BestoAdminWhatsApp.button('Notify founder',founder.whatsappNumber,text);if(button)article.append(button);}
   else{const missing=document.createElement('p');missing.textContent='This founder’s personal link is not available for sharing yet.';article.append(missing);}list.append(article);
  }
  const pending=matches.jobs.some(job=>job.status==='queued'||job.status==='running'),failed=matches.jobs.some(job=>job.status==='failed');notice.textContent=pending?'Checking saved asks for the new operator...':failed?'A new-operator check could not finish. Existing matches are still available.':matches.founders.length?'':'No new top-two matches yet.';
  clearTimeout(timer);if(pending)timer=setTimeout(load,2500);
 }catch{if(current!==version)return;clear();notice.textContent='Could not load payments or new matches. Refresh to try again.';}}
 save.addEventListener('click',async()=>{if(uploading||!file.files[0]){message.textContent='Choose your UPI QR image first.';return;}const selected=file.files[0];if(selected.size>2097152||!['image/png','image/jpeg','image/webp'].includes(selected.type)){message.textContent='Choose a PNG, JPG or WebP under 2 MB.';return;}uploading=true;save.disabled=true;const current=version;message.textContent='Uploading QR code...';try{const {uploadUrl}=await post('payment-upload');if(current!==version)return;const response=await fetch(uploadUrl,{method:'POST',headers:{'Content-Type':selected.type},body:selected,signal:AbortSignal.any([controller.signal,AbortSignal.timeout(15000)])});if(!response.ok)throw Error();const {storageId}=await response.json();if(current!==version)return;await post('payment-save',{storageId});if(current!==version)return;message.textContent='QR code saved.';await load();}catch{if(current===version)message.textContent='Could not upload. Try again.';}finally{if(current===version){uploading=false;save.disabled=false;}}});
 function restart(){version++;controller?.abort();clearTimeout(timer);clear();controller=new AbortController();code=new URLSearchParams(location.hash.slice(1)).get('a');uploading=false;save.disabled=false;if(/^[A-Za-z0-9_-]{43}$/.test(code??''))void load();}
 document.getElementById('founder-notifications-refresh').addEventListener('click',restart);addEventListener('besto:operator-approved',restart);addEventListener('hashchange',restart);addEventListener('pagehide',()=>{version++;controller?.abort();clearTimeout(timer);clear();});addEventListener('pageshow',e=>{if(e.persisted)restart();});restart();
})();
